language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - extra
    - add-on

    # The BuildTools version used by your project
    - build-tools-25.0.3

    # The SDK version used to compile your project
    - android-26
   
   licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    
script:
   - ./gradlew build --stacktrace
