language: android
sudo: false
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services

    # The SDK version used to compile your project
    - android-16
    - android-21
    - android-22
    - android-25
    - android-26

    # Additional components

jdk: oraclejdk8

script:
  - ./gradlew --stacktrace
